language: ruby
rvm:
- 1.9.3
script: bundle exec jekyll build
install: bundle install
after_success: bundle exec s3_website push --force
env:
  global:
  - secure: XUP5pjOFvdj3wSNALuXU8HMBOqsM+r1BeRs1+KOzc2M13TqZUx0gPv6wyQ2P0Dz0qnBHrSLVh30h2IJyc6Ht7153Kg4ZhhTDowtM7MBPu5rVtFVLaYGYy5Ahp/yT7M3gTotekxcc7IzWmisnogwiPkXLCVHTSWayjvh5dkE/7IE=
  - secure: C25xqIR/DfunQypcmldKq+1cLX6dGuBAlEngm6d4H9iTfTbb893pRS3uXztqP5yAf5S2qmzPVQaoOeU7iAGGscNXzQmhLWQBcaJsVQC1sgYxNqYlcVp0g2+1qCp9jnP3i18fcJh79hjBiZgwn596x408goM80aQWu0axBs3SQrs=
